name: Demo Workflow Using Custom Action
on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  greet:
    environment:
      name: "Development"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Run custom Hello World action
        id: greet_step
        uses: ./.github/actions/hello-world
        with:
          name: Rui
